/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreesRouteImport } from './routes/trees'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppFollowsRouteImport } from './routes/app/follows'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCallRouteImport } from './routes/app/call'

const TreesRoute = TreesRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFollowsRoute = AppFollowsRouteImport.update({
  id: '/app/follows',
  path: '/app/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/app/call',
  path: '/app/call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/trees': typeof TreesRoute
  '/app/call': typeof AppCallRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/follows': typeof AppFollowsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/trees': typeof TreesRoute
  '/app/call': typeof AppCallRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/follows': typeof AppFollowsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/trees': typeof TreesRoute
  '/app/call': typeof AppCallRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/follows': typeof AppFollowsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/trees'
    | '/app/call'
    | '/app/dashboard'
    | '/app/follows'
    | '/app/history'
    | '/app/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/trees'
    | '/app/call'
    | '/app/dashboard'
    | '/app/follows'
    | '/app/history'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/trees'
    | '/app/call'
    | '/app/dashboard'
    | '/app/follows'
    | '/app/history'
    | '/app/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  TreesRoute: typeof TreesRoute
  AppCallRoute: typeof AppCallRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFollowsRoute: typeof AppFollowsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trees': {
      id: '/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof TreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/follows': {
      id: '/app/follows'
      path: '/app/follows'
      fullPath: '/app/follows'
      preLoaderRoute: typeof AppFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/call': {
      id: '/app/call'
      path: '/app/call'
      fullPath: '/app/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  TreesRoute: TreesRoute,
  AppCallRoute: AppCallRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFollowsRoute: AppFollowsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
